### ISSUE TITLE
Geocoding / Searching on Map is not working

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#240]
### Steps to Reproduce

 * Type in "Yuba City" in the search. Hit Enter.

### Expected Behavior

 * Map goes to Yuba City

### Actual Behavior

 * Nothing happens

### Demo

![2017-06-29 10 00 25](https://user-images.githubusercontent.com/1430060/27691404-e20b4cd8-5cb1-11e7-8f85-f4038b12bf4e.gif)

**Comment by rajadain** [comment]
Also seeing these test failures:

```
> kj test
+ vagrant ssh app -c 'flake8 /opt/app/apps --exclude migrations || echo flake8 check failed'
Connection to 127.0.0.1 closed.
+ vagrant ssh app -c 'cd /opt/app && envdir /etc/icp.d/env ./manage.py test --noinput'
Creating test database for alias 'default'...
FF.Not Found: /project/2/clone
.Not Found: /project/3/
.......Not Found: /project/9/clone
.Not Found: /project/10/
.............................................
======================================================================
FAIL: test_geocoder_returns_a_gazetteer_response (app.apps.geocode.tests.GeocodeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/apps/geocode/tests.py", line 23, in test_geocoder_returns_a_gazetteer_response
    self.assert_candidate_exists_for('The White House')
  File "/opt/app/apps/geocode/tests.py", line 19, in assert_candidate_exists_for
    self.assertTrue(len(response) > 0, 'Expected '
AssertionError: Expected at least 1 candidate in the response

======================================================================
FAIL: test_geocoder_returns_an_address_response (app.apps.geocode.tests.GeocodeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/apps/geocode/tests.py", line 26, in test_geocoder_returns_an_address_response
    self.assert_candidate_exists_for('320 north 12th st philadelphia')
  File "/opt/app/apps/geocode/tests.py", line 19, in assert_candidate_exists_for
    self.assertTrue(len(response) > 0, 'Expected '
AssertionError: Expected at least 1 candidate in the response

----------------------------------------------------------------------
Ran 57 tests in 14.644s

FAILED (failures=2)
Destroying test database for alias 'default'...
Connection to 127.0.0.1 closed.
kj: callProcess: ./scripts/test.sh (exit 1): failed
```

**Comment by rajadain** [comment]
See related https://github.com/azavea/python-omgeo/pull/30

**Comment by hectcastro** [comment]
Fixed by https://github.com/project-icp/bee-pollinator-app/pull/241
