### ISSUE TITLE
Evaluate Using Beescape Storage

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#616]
Penn would like to host the rasters internally, instead of S3. See if this is possible.

**Comment by rajadain** [comment]
I've been working on upgrading Ubuntu to get the project to provision locally. That work is in this branch: [`tt/ubuntu-upgrade-16.06`](https://github.com/project-icp/bee-pollinator-app/tree/tt/ubuntu-upgrade-16.04). Currently running in to this issue, which is likely a conflict between Django and `libproj-dev`:

```
:stderr: Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python2.7/dist-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 241, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 112, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/postgis/base.py", line 8, in <module>
    from .features import DatabaseFeatures
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/models/__init__.py", line 7, in <module>
    from django.contrib.gis.geos import HAS_GEOS
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/__init__.py", line 8, in <module>
    from .libgeos import geos_version, geos_version_info  # NOQA: flake8 detects only the last __all__
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/libgeos.py", line 152, in <module>
    _verinfo = geos_version_info()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/libgeos.py", line 147, in geos_version_info
    raise GEOSException('Could not parse version info string "%s"' % ver)
    django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.7.1-CAPI-1.11.1 27a5e771"
```

**Comment by rajadain** [comment]
The Ubuntu upgrade was completed in 340e19a5. I added a changeset 9ed7b243 to demo what switching to HTTPS storage instead of S3 looks like. Pretty straightforward, although we'll probably have to do some secrets engineering to pass in the new host.

Also, the Ubuntu upgrade was done in a very rough manner. Would like an operations engineer to take a look before we try to deploy any of these changes.

![image](https://user-images.githubusercontent.com/1430060/130842967-4d10c938-fde3-4466-82a5-eb5c61afba61.png)

**Comment by rajadain** [comment]
The `libproj-dev` issue was fixed with the following:

https://github.com/project-icp/bee-pollinator-app/blob/9ed7b2433912cd32ddf67ec4e71880e4b581b419/deployment/ansible/roles/bee-pollinator.app/tasks/dependencies.yml#L17-L21
