### ISSUE TITLE
Memory Error When Running Model

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#86]
Encountered while testing #85 on AOIs of varying size

- @mmcfarland can't reproduce

```
[2016-12-22 15:54:23,715: ERROR/Worker-1] Task e601c9cc-e9bb-47e2-8149-838fe284de9a run from job 533 raised exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 46, in calculate_yield
    modifications, managed_hives)
  File "/usr/local/lib/python2.7/dist-packages/pollinator-0.1.0-py2.7.egg/pollinator/crop_yield.py", line 172, in calculate
    area_abundance = abundance(cdl)
  File "/usr/local/lib/python2.7/dist-packages/pollinator-0.1.0-py2.7.egg/pollinator/crop_yield.py", line 102, in abundance
    function=focal_op)
  File "/usr/local/lib/python2.7/dist-packages/scipy/ndimage/filters.py", line 1245, in generic_filter
    cval, origins, extra_arguments, extra_keywords)
MemoryError
```

**Comment by arottersman** [comment]
I had Spark Job Server still running on my worker VM. It was eating up all my memory. Fixed by destroying worker and rebuilding.
